import { createHash } from "node:crypto";
import { nanoid } from "nanoid";
import postgres, { type Sql } from "postgres";
import { childViewType, viewEdgeLabelErrors, viewNodeKindErrors, type CreateTraceInput, type CreateViewInput, type Evidence, type KnowledgeSearchResult, type KnowledgeTrace, type KnowledgeView, type McpToken, type Repository, type TraceStep, type ViewEdge, type ViewEdgeInput, type ViewNode, type ViewNodeInput } from "@cartograph/shared";
import { validateTrace } from "./trace-validation.js";

const now = () => new Date().toISOString();
const repoId = (ownerId: string, externalId: string) => `repo_${createHash("sha256").update(`${ownerId}:${externalId}`).digest("hex").slice(0, 16)}`;

export class PostgresStore {
  readonly sql: Sql;
  constructor(url: string) { this.sql = postgres(url, { max: Number(process.env.DB_POOL_SIZE ?? 10), ssl: process.env.NODE_ENV === "production" ? "require" : "prefer" }); }
  forUser(userId: string) { return new PostgresTenantStore(this.sql, userId); }
  async resolveMcpToken(tokenHash: string) { const [row] = await this.sql<{ id: string; owner_id: string }[]>`UPDATE mcp_tokens SET last_used_at=now() WHERE token_hash=${tokenHash} RETURNING id,owner_id`; return row ? { userId: row.owner_id, tokenId: row.id } : undefined; }
}

export class PostgresTenantStore {
  constructor(private sql: Sql, readonly userId: string) {}
  async repositories(): Promise<Repository[]> { return (await this.sql`SELECT id,name,external_id,added_at FROM repositories WHERE owner_id=${this.userId} ORDER BY added_at DESC`).map(repoFromRow); }
  async repository(id: string): Promise<Repository | null> { const [row] = await this.sql`SELECT id,name,external_id,added_at FROM repositories WHERE id=${id} AND owner_id=${this.userId}`; return row ? repoFromRow(row) : null; }
  async registerRepository(input: { name: string; externalId?: string }): Promise<Repository> { const externalId = input.externalId?.trim() || input.name.trim().toLowerCase(); const id = repoId(this.userId, externalId); const [row] = await this.sql`INSERT INTO repositories(id,owner_id,name,external_id) VALUES(${id},${this.userId},${input.name},${externalId}) ON CONFLICT(owner_id,external_id) DO UPDATE SET name=excluded.name RETURNING id,name,external_id,added_at`; return repoFromRow(row!); }
  async deleteRepository(id: string) { return (await this.sql`DELETE FROM repositories WHERE id=${id} AND owner_id=${this.userId}`).count > 0; }
  async views(repositoryId?: string, includeArchived = false): Promise<KnowledgeView[]> { const rows = repositoryId ? await this.sql`SELECT id FROM views WHERE owner_id=${this.userId} AND repository_id=${repositoryId} AND (${includeArchived} OR archived_at IS NULL) ORDER BY updated_at DESC` : await this.sql`SELECT id FROM views WHERE owner_id=${this.userId} AND (${includeArchived} OR archived_at IS NULL) ORDER BY updated_at DESC`; return Promise.all(rows.map(row => this.view(String(row.id)))).then(items => items.filter((item): item is KnowledgeView => Boolean(item))); }
  async searchKnowledge(repositoryId: string, query: string, limit = 40): Promise<KnowledgeSearchResult[]> { await this.requireRepository(repositoryId); const normalized = query.trim().toLowerCase(); if (!normalized) return []; const results: KnowledgeSearchResult[] = []; for (const view of await this.views(repositoryId)) { if (`${view.title} ${view.description}`.toLowerCase().includes(normalized)) results.push({ id: `view:${view.id}`, type: "view", label: view.title, detail: view.description || `${view.nodes.length} entities`, viewId: view.id }); for (const node of view.nodes) if (`${node.label} ${node.summary} ${node.kind}`.toLowerCase().includes(normalized)) results.push({ id: `node:${view.id}:${node.id}`, type: "node", label: node.label, detail: `${view.title} · ${node.kind}`, viewId: view.id, nodeId: node.id }); } return results.slice(0, Math.min(limit, 100)); }
  async view(id: string): Promise<KnowledgeView | null> { const [row] = await this.sql`SELECT * FROM views WHERE id=${id} AND owner_id=${this.userId}`; if (!row) return null; const graph = graphFrom(row.graph); const children = await this.sql`SELECT id,parent_node_id FROM views WHERE parent_view_id=${id} AND archived_at IS NULL`; const childByNode = new Map(children.map(child => [String(child.parent_node_id), String(child.id)])); return { id: String(row.id), repositoryId: String(row.repository_id), title: String(row.title), description: String(row.description), viewType: String(row.view_type ?? "custom") as KnowledgeView["viewType"], scope: String(row.scope ?? ""), parentViewId: row.parent_view_id ? String(row.parent_view_id) : undefined, parentNodeId: row.parent_node_id ? String(row.parent_node_id) : undefined, ancestors: await this.ancestors(id), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), revision: Number(row.revision), archivedAt: row.archived_at ? iso(row.archived_at) : undefined, nodes: graph.nodes.map(node => ({ ...node, childViewId: childByNode.get(node.id) })), edges: graph.edges }; }
  async createView(input: CreateViewInput): Promise<KnowledgeView> { await this.requireRepository(input.repositoryId); if (input.parentViewId) { const parent = await this.requireView(input.parentViewId); if (parent.repositoryId !== input.repositoryId || !parent.nodes.some(node => node.id === input.parentNodeId)) throw new Error("Parent node not found"); } const id = nanoid(12); const graph = makeGraph(input.nodes, input.edges); await this.sql`INSERT INTO views(id,owner_id,repository_id,title,description,view_type,scope,parent_view_id,parent_node_id,graph) VALUES(${id},${this.userId},${input.repositoryId},${input.title},${input.description},${input.viewType},${input.scope},${input.parentViewId ?? null},${input.parentNodeId ?? null},${this.sql.json(toJson(graph))})`; return (await this.view(id))!; }
  async extendView(id: string, nodes: ViewNodeInput[], edges: ViewEdgeInput[], expectedRevision?: number) { const current = await this.requireView(id); assertRevision(current, expectedRevision); const semanticErrors = [...viewNodeKindErrors(current.viewType, nodes), ...viewEdgeLabelErrors(current.viewType, edges)]; if (semanticErrors.length) throw new Error(semanticErrors.join("\n")); const graph = mergeGraph(current.nodes, current.edges, nodes, edges); const rows = await this.sql`UPDATE views SET graph=${this.sql.json(toJson(graph))},revision=revision+1,updated_at=now() WHERE id=${id} AND owner_id=${this.userId} AND revision=${current.revision} RETURNING id`; if (!rows.length) throw new Error("Revision conflict"); return (await this.view(id))!; }
  async updateView(id: string, input: { title?: string; description?: string; expectedRevision?: number }) { const current = await this.requireView(id); assertRevision(current, input.expectedRevision); await this.sql`UPDATE views SET title=${input.title ?? current.title},description=${input.description ?? current.description},revision=revision+1,updated_at=now() WHERE id=${id} AND owner_id=${this.userId} AND revision=${current.revision}`; return (await this.view(id))!; }
  async updateNodePositions(id: string, positions: { id: string; x: number; y: number }[], expectedRevision?: number, routes?: { id: string; route: unknown }[], clearRoutes = false) { const current = await this.requireView(id); assertRevision(current, expectedRevision); const byPosition = new Map(positions.map(item => [item.id, item])); const byRoute = new Map(routes?.map(item => [item.id, item.route])); const graph = { nodes: current.nodes.map(node => ({ ...node, position: byPosition.get(node.id) ? { x: byPosition.get(node.id)!.x, y: byPosition.get(node.id)!.y } : node.position })), edges: current.edges.map(edge => ({ ...edge, route: clearRoutes ? undefined : byRoute?.has(edge.id) ? byRoute.get(edge.id) as ViewEdge["route"] : edge.route })) }; await this.sql`UPDATE views SET graph=${this.sql.json(graph)},revision=revision+1,updated_at=now() WHERE id=${id} AND owner_id=${this.userId} AND revision=${current.revision}`; return (await this.view(id))!; }
  async duplicateView(id: string) { const current = await this.requireView(id); return this.createView({ repositoryId: current.repositoryId, title: `${current.title} copy`, description: current.description, viewType: current.viewType, scope: current.scope, nodes: current.nodes, edges: current.edges }); }
  async createNodeDrilldown(viewId: string, nodeId: string) { const parent = await this.requireView(viewId); const node = parent.nodes.find(item => item.id === nodeId); if (!node) throw new Error("Node not found"); if (node.childViewId) return (await this.view(node.childViewId))!; return this.createView({ repositoryId: parent.repositoryId, parentViewId: viewId, parentNodeId: nodeId, title: node.label, description: `Inside ${node.label}`, viewType: childViewType(parent.viewType, node.kind), scope: node.label, nodes: [], edges: [] }); }
  async traces(viewId: string): Promise<KnowledgeTrace[]> { await this.requireView(viewId); return (await this.sql`SELECT * FROM traces WHERE owner_id=${this.userId} AND view_id=${viewId} ORDER BY updated_at DESC`).map(traceFromRow); }
  async trace(id: string): Promise<KnowledgeTrace | null> { const [row] = await this.sql`SELECT * FROM traces WHERE id=${id} AND owner_id=${this.userId}`; return row ? traceFromRow(row) : null; }
  async createTrace(input: CreateTraceInput) { const view = await this.requireView(input.viewId); validateTrace(view, input); const id = nanoid(12); const steps = redactSteps(input.steps); await this.sql`INSERT INTO traces(id,owner_id,view_id,title,description,steps) VALUES(${id},${this.userId},${input.viewId},${input.title},${input.description},${this.sql.json(toJson(steps))})`; return (await this.trace(id))!; }
  async deleteTrace(id: string) { return (await this.sql`DELETE FROM traces WHERE id=${id} AND owner_id=${this.userId}`).count > 0; }
  async archiveView(id: string, expectedRevision?: number) { const current = await this.requireView(id); assertRevision(current, expectedRevision); await this.sql`UPDATE views SET archived_at=now(),updated_at=now(),revision=revision+1 WHERE id=${id} AND owner_id=${this.userId} AND revision=${current.revision}`; return (await this.view(id))!; }
  async deleteView(id: string) { return (await this.sql`DELETE FROM views WHERE id=${id} AND owner_id=${this.userId}`).count > 0; }
  async mcpTokens(): Promise<McpToken[]> { return (await this.sql`SELECT id,name,prefix,created_at,last_used_at FROM mcp_tokens WHERE owner_id=${this.userId} ORDER BY created_at DESC`).map(tokenFromRow); }
  async createMcpToken(input: { id: string; name: string; prefix: string; tokenHash: string }) { const [row] = await this.sql`INSERT INTO mcp_tokens(id,owner_id,name,prefix,token_hash) VALUES(${input.id},${this.userId},${input.name},${input.prefix},${input.tokenHash}) RETURNING id,name,prefix,created_at,last_used_at`; return tokenFromRow(row!); }
  async deleteMcpToken(id: string) { return (await this.sql`DELETE FROM mcp_tokens WHERE id=${id} AND owner_id=${this.userId}`).count > 0; }
  private async requireRepository(id: string) { const value = await this.repository(id); if (!value) throw new Error("Repository not found"); return value; }
  private async requireView(id: string) { const value = await this.view(id); if (!value) throw new Error("View not found"); return value; }
  private async ancestors(id: string): Promise<KnowledgeView["ancestors"]> { const rows = await this.sql`WITH RECURSIVE chain AS (SELECT id,parent_view_id,parent_node_id,0 depth FROM views WHERE id=${id} AND owner_id=${this.userId} UNION ALL SELECT v.id,v.parent_view_id,v.parent_node_id,c.depth+1 FROM views v JOIN chain c ON v.id=c.parent_view_id WHERE v.owner_id=${this.userId}) SELECT p.id view_id,p.title,p.graph,c.parent_node_id node_id,c.depth FROM chain c JOIN views p ON p.id=c.parent_view_id WHERE c.parent_view_id IS NOT NULL ORDER BY c.depth DESC`; return rows.flatMap(row => { const node = graphFrom(row.graph).nodes.find(item => item.id === String(row.node_id)); return node ? [{ viewId: String(row.view_id), title: String(row.title), nodeId: node.id, nodeLabel: node.label }] : []; }); }
}

function makeGraph(nodes: ViewNodeInput[], edges: ViewEdgeInput[]) { return { nodes: nodes.map((node, index) => ({ ...node, id: node.id ?? nanoid(10), position: node.position ?? { x: 120 + (index % 3) * 280, y: 100 + Math.floor(index / 3) * 180 } })) as ViewNode[], edges: edges.map(edge => ({ ...edge, id: edge.id ?? nanoid(10) })) as ViewEdge[] }; }
function mergeGraph(currentNodes: ViewNode[], currentEdges: ViewEdge[], nodes: ViewNodeInput[], edges: ViewEdgeInput[]) { const added = makeGraph(nodes, edges); const nodeMap = new Map(currentNodes.map(node => [node.id, node])); for (const node of added.nodes) nodeMap.set(node.id, { ...nodeMap.get(node.id), ...node }); const edgeMap = new Map(currentEdges.map(edge => [edge.id, edge])); for (const edge of added.edges) edgeMap.set(edge.id, { ...edgeMap.get(edge.id), ...edge }); return { nodes: [...nodeMap.values()], edges: [...edgeMap.values()] }; }
function graphFrom(value: unknown): { nodes: ViewNode[]; edges: ViewEdge[] } { const graph = typeof value === "string" ? JSON.parse(value) : value; return graph as { nodes: ViewNode[]; edges: ViewEdge[] }; }
function toJson(value: unknown): import("postgres").JSONValue { return JSON.parse(JSON.stringify(value)) as import("postgres").JSONValue; }
function repoFromRow(row: Record<string, unknown>): Repository { return { id: String(row.id), name: String(row.name), externalId: String(row.external_id), addedAt: iso(row.added_at) }; }
function traceFromRow(row: Record<string, unknown>): KnowledgeTrace { return { id: String(row.id), viewId: String(row.view_id), title: String(row.title), description: String(row.description), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), steps: (typeof row.steps === "string" ? JSON.parse(row.steps) : row.steps) as TraceStep[] }; }
function tokenFromRow(row: Record<string, unknown>): McpToken { return { id: String(row.id), name: String(row.name), prefix: String(row.prefix), createdAt: iso(row.created_at), lastUsedAt: row.last_used_at ? iso(row.last_used_at) : undefined }; }
function iso(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
function assertRevision(view: KnowledgeView, expected?: number) { if (expected && view.revision !== expected) throw new Error(`Revision conflict: expected ${expected}, found ${view.revision}`); }
const secretField = /(^|[_-])(password|passwd|secret|token|api[_-]?key|authorization|cookie|private[_-]?key)($|[_-])/i;
function redact<T>(value: T): T { if (Array.isArray(value)) return value.map(redact) as T; if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, secretField.test(key) ? "[REDACTED]" : redact(item)])) as T; return value; }
function redactSteps(steps: CreateTraceInput["steps"]): TraceStep[] { return steps.map((step, index) => ({ ...step, id: step.id ?? `step-${index + 1}`, payload: step.payload ? { ...step.payload, before: redact(step.payload.before), after: redact(step.payload.after), fields: step.payload.fields.map(field => ({ ...field, before: redact(field.before), after: redact(field.after) })) } : undefined })); }
